---
title: "Demonstration 1"
output:
  html_document:
    toc: true
  html_notebook: default
---

###Подключаем требуемые пакеты

```{r, message=FALSE, warning=FALSE}

library(igraph)
library(pagoda2)
library(ggplot2)
#library(magrittr)
library(pbapply)

theme_set(theme_bw())

set.seed(2018)

```

### Меняем PCA

```{r}

path_floder <- DataPath("filtered_gene_bc_matrices/GRCh38")

load_matrix <- pagoda2::read.10x.matrices(path_floder)
load_matrix <- load_matrix[!duplicated(rownames(load_matrix)),]

```
```{r}

pagoda_data <- pagoda2::basicP2proc(load_matrix, n.cores=10)

```
### Изначальный граф
```{r}

all_clusters_multilevel <- pagoda_data$clusters$PCA$multilevel
all_clusters_infomap <- pagoda_data$clusters$PCA$infomap

```
```{r}

#изначальный граф без разметки
conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE)

#изначальный граф с разметкой multilevel
conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE, groups=all_clusters_multilevel)

#изначальный граф с разметкой infomap
conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE, groups=all_clusters_infomap)

```
### Уточнение произведенное по кластеризации infomap
```{r}

update_pagoda_data_infomap <- UpdatePagoda(primary.data = load_matrix, pagoda.obj = pagoda_data,
                                           clustering.type='infomap', k= c(30, 30, 30), n.cores=20)

```
```{r}

update_pagoda_data_infomap$getEmbedding(type = "PCA", perplexity = 30, embeddingType = "tSNE",
                                        max_iter = 1000)

```
```{r}

# уточненный граф без разметки
conos::embeddingPlot(update_pagoda_data_infomap$embeddings$PCA$tSNE)

# уточненный граф с новой разметкой
conos::embeddingPlot(update_pagoda_data_infomap$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_infomap$clusters$PCA$infomap)

# уточненный граф с изначальной разметкой
conos::embeddingPlot(update_pagoda_data_infomap$embeddings$PCA$tSNE, groups=all_clusters_infomap)

```
### Уточнение произведенное по кластеризации multilevel
```{r}

update_pagoda_data_multilevel <- UpdatePagoda(primary.data = load_matrix, pagoda.obj = pagoda_data,
                                   clustering.type='multilevel', k=c(25, 20, 15), n.cores=20)

```
```{r}

update_pagoda_data_multilevel$getKnnClusters(method = igraph::infomap.community,
                                             type = "PCA", name = "infomap")

```
```{r}

# уточненный граф без разметки
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE)

# уточненный граф с новой разметкой
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel$clusters$PCA$infomap)

# уточненный граф с изначальной разметкой
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE, groups=all_clusters_infomap)

```

