title: "Demonstration 2"
output:
  html_document:
    toc: true
  html_notebook: default
---

###Подключаем требуемые пакеты

```{r, message=FALSE, warning=FALSE}

library(igraph)
library(pagoda2)
library(ggplot2)
#library(magrittr)
library(pbapply)

theme_set(theme_bw())

set.seed(2018)

```

### Меняем PCA

```{r}

path_floder <- DataPath("GSE109447_13055_cm.rds")

load_matrix <- readRDS(path_floder)
load_matrix <- load_matrix[!duplicated(rownames(load_matrix)),]

```
```{r}

pagoda_data <- pagoda2::basicP2proc(load_matrix, n.cores=10)

```
### Изначальный граф
```{r}

all_clusters_multilevel <- pagoda_data$clusters$PCA$multilevel
all_clusters_infomap <- pagoda_data$clusters$PCA$infomap

```
```{r}

#изначальный граф без разметки
conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE)

#изначальный граф с разметкой multilevel
conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE, groups=all_clusters_multilevel)

#изначальный граф с разметкой infomap
conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE, groups=all_clusters_infomap)

```
### Уточнение произведенное по кластеризации multilevel
```{r}

update_pagoda_data_multilevel <- UpdatePagoda(primary.data = load_matrix, pagoda.obj = pagoda_data,
                                   clustering.type='multilevel', k= c(30, 30, 30), n.cores=20)

```
```{r}

update_pagoda_data_multilevel$getKnnClusters(method = igraph::infomap.community,
                                             type = "PCA", name = "infomap", n.cores=20)

```
```{r}

# уточненный граф без разметки
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE)

# уточненный граф с новой разметкой
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel$clusters$PCA$infomap)

# уточненный граф с изначальной разметкой
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE, groups=all_clusters_infomap)

# уточненный граф с новой разметкой
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel$clusters$PCA$multilevel)

# уточненный граф с изначальной разметкой
conos::embeddingPlot(update_pagoda_data_multilevel$embeddings$PCA$tSNE, groups=all_clusters_multilevel)

```

#### Смотрим как строятся графы для кластеров и их окрестностей

```{r}

pagoda_data <- pagoda2::basicP2proc(load_matrix)

```
```{r}

clusters <- pagoda_data$clusters$PCA$multilevel
clusters_name <- pbapply::pblapply(levels(clusters), ClusterNeighborhood, clusters, pagoda_data, cl= 16)

```
```{r}
# improvement clusters

pagoda_for_clusters <- pbapply::pblapply(1:length(levels(clusters)), function(id)
  GetPagoda(load_matrix[,clusters_name[[id]]$expand_cluster], embeding.type = NULL, k = 60,
            n.pcs = max(round(length(clusters_name[[id]]$expand_cluster)/45), 5) ))

#cluster_graph <- GetPagoda(load_matrix[,clusters_name[[6]]$expand_cluster], k=60,
#                           n.pcs = max(round(length(clusters_name[[6]]$expand_cluster)/45), 5))

```
```{r}

cluster_graph$getKnnClusters(method = igraph::multilevel.community, type = "PCA", name = "multilevel")
cluster_graph$getKnnClusters(method = igraph::infomap.community, type = "PCA", name = "infomap")

conos::embeddingPlot(cluster_graph$embeddings$PCA$tSNE)

conos::embeddingPlot(cluster_graph$embeddings$PCA$tSNE, groups = pagoda_data$clusters$PCA$multilevel)
conos::embeddingPlot(cluster_graph$embeddings$PCA$tSNE, groups = cluster_graph$clusters$PCA$multilevel)

conos::embeddingPlot(cluster_graph$embeddings$PCA$tSNE, groups = pagoda_data$clusters$PCA$infomap)
conos::embeddingPlot(cluster_graph$embeddings$PCA$tSNE, groups = cluster_graph$clusters$PCA$infomap)
```
```{r}
```