---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

###Подключаем требуемые пакеты

```{r, message=FALSE, warning=FALSE}

library(igraph)
library(pagoda2)
library(ggplot2)
library(magrittr)
library(pbapply)

theme_set(theme_bw())

set.seed(2018)

```

### Считываем данные и строим граф

```{r}
path_floder <- DataPath("filtered_gene_bc_matrices/GRCh38")

load_matrix <- pagoda2::read.10x.matrices(path_floder)
load_matrix <- load_matrix[!duplicated(rownames(load_matrix)),]
pagoda_data <- pagoda2::basicP2proc(load_matrix)

```
```{r}

all_clusters_multilevel <- pagoda_data$clusters$PCA$multilevel
all_clusters_infomap <- pagoda_data$clusters$PCA$infomap

conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE)

conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE, groups=all_clusters_multilevel)
conos::embeddingPlot(pagoda_data$embeddings$PCA$tSNE, groups=all_clusters_infomap)

conos::embeddingPlot(pagoda_data$embeddings$PCA$largeVis, groups=all_clusters_multilevel)
conos::embeddingPlot(pagoda_data$embeddings$PCA$largeVis, groups=all_clusters_infomap)

```

### Уточняем по кластеризации multilevel

```{r}

update_pagoda_data_multilevel_1 <- UpdatePagoda(primary.data = load_matrix, pagoda.obj = pagoda_data,
                                                clustering.type='multilevel', count.iter = 1)

update_pagoda_data_multilevel_1$getKnnClusters(method = igraph::infomap.community,
                                               type = "PCA", name = "infomap")

```
```{r}

conos::embeddingPlot(update_pagoda_data_multilevel_1$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel_1$clusters$PCA$multilevel)
conos::embeddingPlot(update_pagoda_data_multilevel_1$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel_1$clusters$PCA$infomap)

```

```{r}

update_pagoda_data_multilevel_3 <- UpdatePagoda(primary.data = load_matrix,
                                                pagoda.obj = update_pagoda_data_multilevel_1,
                                                clustering.type='multilevel', count.iter = 2)

update_pagoda_data_multilevel_3$getKnnClusters(method = igraph::infomap.community,
                                               type = "PCA", name = "infomap")

```
```{r}

conos::embeddingPlot(update_pagoda_data_multilevel_3$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel_3$clusters$PCA$multilevel)
conos::embeddingPlot(update_pagoda_data_multilevel_3$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel_3$clusters$PCA$infomap)

```

```{r}

update_pagoda_data_multilevel_5 <- UpdatePagoda(primary.data = load_matrix,
                                                pagoda.obj = update_pagoda_data_multilevel_3,
                                                clustering.type='multilevel', count.iter = 2)

update_pagoda_data_multilevel_5$getKnnClusters(method = igraph::infomap.community,
                                               type = "PCA", name = "infomap")

```
```{r}

conos::embeddingPlot(update_pagoda_data_multilevel_5$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel_5$clusters$PCA$multilevel)
conos::embeddingPlot(update_pagoda_data_multilevel_5$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_multilevel_5$clusters$PCA$infomap)

```

```{r}

conos::embeddingPlot(update_pagoda_data_multilevel_5$embeddings$PCA$tSNE)
conos::embeddingPlot(update_pagoda_data_multilevel_5$embeddings$PCA$tSNE,
                     groups=all_clusters_infomap)

```

### Уточняем по кластеризации infomap

### Строим заново исходный граф
```{r}

pagoda_data_second_var <- pagoda2::basicP2proc(load_matrix)

```
```{r}

all_clusters_multilevel <- pagoda_data_second_var$clusters$PCA$multilevel
all_clusters_infomap <- pagoda_data_second_var$clusters$PCA$infomap

conos::embeddingPlot(pagoda_data_second_var$embeddings$PCA$tSNE)

conos::embeddingPlot(pagoda_data_second_var$embeddings$PCA$tSNE, groups=all_clusters_multilevel)
conos::embeddingPlot(pagoda_data_second_var$embeddings$PCA$tSNE, groups=all_clusters_infomap)

conos::embeddingPlot(pagoda_data_second_var$embeddings$PCA$largeVis, groups=all_clusters_multilevel)
conos::embeddingPlot(pagoda_data_second_var$embeddings$PCA$largeVis, groups=all_clusters_infomap)

```

```{r}

update_pagoda_data_infomap_1 <- UpdatePagoda(primary.data = load_matrix,
                                             pagoda.obj = pagoda_data_second_var,
                                             clustering.type='infomap', count.iter = 1)

update_pagoda_data_infomap_1$getKnnClusters(method = igraph::multilevel.community,
                                               type = "PCA", name = "multilevel")

```
```{r}

conos::embeddingPlot(update_pagoda_data_infomap_1$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_infomap_1$clusters$PCA$multilevel)
conos::embeddingPlot(update_pagoda_data_infomap_1$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_infomap_1$clusters$PCA$infomap)

```

```{r}

update_pagoda_data_infomap_3 <- UpdatePagoda(primary.data = load_matrix,
                                             pagoda.obj = update_pagoda_data_infomap_1,
                                             clustering.type='infomap', count.iter = 2)

update_pagoda_data_infomap_3$getKnnClusters(method = igraph::multilevel.community,
                                               type = "PCA", name = "multilevel")

```
```{r}

conos::embeddingPlot(update_pagoda_data_infomap_3$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_infomap_3$clusters$PCA$multilevel)
conos::embeddingPlot(update_pagoda_data_infomap_3$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_infomap_3$clusters$PCA$infomap)

```

```{r}

update_pagoda_data_infomap_5 <- UpdatePagoda(primary.data = load_matrix,
                                             pagoda.obj = update_pagoda_data_infomap_3,
                                             clustering.type='infomap', count.iter = 2)

update_pagoda_data_infomap_5$getKnnClusters(method = igraph::multilevel.community,
                                               type = "PCA", name = "multilevel")

```
```{r}

conos::embeddingPlot(update_pagoda_data_infomap_5$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_infomap_5$clusters$PCA$multilevel)
conos::embeddingPlot(update_pagoda_data_infomap_5$embeddings$PCA$tSNE,
                     groups=update_pagoda_data_infomap_5$clusters$PCA$infomap)

```

```{r}

conos::embeddingPlot(update_pagoda_data_infomap_5$embeddings$PCA$tSNE)
conos::embeddingPlot(update_pagoda_data_infomap_5$embeddings$PCA$tSNE, groups=all_clusters_infomap)

```
